name: hydrone_navigation
root: ./
startup_window: simulation
windows:
  - connection:
      layout: tiled
      panes:
        - roslaunch airsim_ros_pkgs airsim_node.launch output:=screen host:='172.18.0.3'

  - simulation:
      layout: tiled
      panes:
        - sleep 4; roslaunch detection generate_dataset.launch

  
